# Generated by Django 4.2.7 on 2023-12-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
